env               = "prod"
aws_region        = "ca-central-1"
db_instance_class = "db.t4g.medium"
domain_name       = "autobook.tech"
api_subdomain     = "api"
github_repo       = "your-org/autobook"
alert_email       = "autobook@pm.me"
